/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface AccumulatorConfig {
  maxFecSetsPerSlot?: number
  stuckBatchTimeoutMs?: number
}
export interface ListenerOptions {
  recvBuf?: number
  maxAge?: bigint
  busyPollUs?: number
  disableBusyPoll?: boolean
  poolSize?: number
  enableFec?: boolean
  disableSalvageDelivery?: boolean
  accumulator?: AccumulatorConfig
}
export const enum VariantKind {
  DataLegacy = 'DataLegacy',
  CodeLegacy = 'CodeLegacy',
  DataMerkleUnchained = 'DataMerkleUnchained',
  DataMerkleResigned = 'DataMerkleResigned',
  CodeMerkleUnchained = 'CodeMerkleUnchained',
  CodeMerkleResigned = 'CodeMerkleResigned'
}
export declare function classifyVariant(byte: number): VariantKind | null
export declare function variantProofSize(byte: number): number
export declare function variantResigned(byte: number): boolean
export declare function variantMerkleSuffix(byte: number): number
export declare function pinCurrentThreadToCpu(cpuId: number): void
export interface TransactionBatch {
  slot: bigint
  transactions: Array<Buffer>
}
export interface RawShred {
  slot: bigint
  index: number
  payloadLen: number
}
export declare class ShredListener {
  static bind(port: number): ShredListener
  static bindWithOptions(port: number, opts: ListenerOptions): ShredListener
  static offline(): ShredListener
  static fromFd(fd: number, opts: ListenerOptions): ShredListener
  nextTransactionSync(): TransactionBatch | null
  nextTransaction(): Promise<TransactionBatch | null>
  nextShred(): Promise<RawShred | null>
  handlePacket(data: Buffer): TransactionBatch | null
  close(): void
  get slotCount(): number
  get poolExhaustedCount(): bigint
  get busyPollActive(): boolean
  get lastIoErrorKind(): string | null
  get dataShredCountTotal(): bigint
  get codeShredCountTotal(): bigint
  get bytesReceived(): bigint
  get unparseablePackets(): bigint
  get unparseableTooShort(): bigint
  get unparseableVariant(): bigint
  get unparseablePayload(): bigint
  get unparseableSlotRange(): bigint
  get droppedKnownSlots(): bigint
  get harvestedBatchesTotal(): bigint
  get decodeErrorsTotal(): bigint
  get fecRecoveriesTotal(): bigint
  get fecRecoveryFailuresTotal(): bigint
  get batchesSkippedTotal(): bigint
  get batchesDecodedStreamingTotal(): bigint
  get batchesDecodedFallbackTotal(): bigint
  get slotsCompletedTotal(): bigint
  get slotsEvictedByAge(): bigint
  get salvagedTailTxTotal(): bigint
  get fecSetsDiscardedUnusedTotal(): bigint
  get fecSetsEvictedEarlyTotal(): bigint
  get batchesForceFinalizedCorruptedTotal(): bigint
  get batchesForceFinalizedTimeoutTotal(): bigint
  get localAddress(): string | null
}
